version: '3'
services:
 vam_webconfig-api:
  build: .
  image: node-example:latest
  labels:
        - "traefik.backend=webconfig-api"
        - "traefik.frontend.entryPoints=legacyapi"
        - "traefik.frontend.rule=PathPrefix:/"
        - "traefik.port=8000"
  environment:
        - PORT=8000
        - DEBUG=http,worker:a,worker:sendData
        - DEBUG_COLORS=true
        - GIT_REPO=git@github.com:mygoodkab/api-analytic-box.git
        - GIT_BRANCH=mongodb
        - GIT_PULL=true
  networks:
        - net_webgateway
        - net_vam-internals
  volumes:
        - ${HOME}/vam-data/:/vam-data/
        - /var/run/docker.sock:/var/run/docker.sock
        - /opt/vam/:/opt/vam/
        - ${HOME}/./git_dir:/usr/local/src
  restart: unless-stopped

networks:
  net_webgateway:
    external:
      name: router_webgateway
  net_vam-internals:
    external:
      name: router_vam-internals
