version: '3'
services:
 vam_webconfig-api:
  build: .
  image: embedded-performance-server.local:5000/eslab/webconfig-api:BACKEND-RFC01-V0.5
  labels:
      - "traefik.backend=webconfig-api"
      - "traefik.frontend.entryPoints=legacyapi"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=8000"
  networks:
      - net_webgateway
      - net_vam-internals
  volumes:
   - ${HOME}/vam-data/:/vam-data/
   - /var/run/docker.sock:/var/run/docker.sock
   - /opt/vam/:/opt/vam/
  restart: unless-stopped

networks:
  net_webgateway:
    external:
      name: router_webgateway
  net_vam-internals:
    external:
      name: router_vam-internals
